---
title: "__TITLE__"
author: "matricaria.suaveolens@gmail.com"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
format:
  html:
    code-fold: true
    toc: true
    embed-resources: true
bibliography:
  - bibliography.bib
  - tools.bib
  - grateful-refs.bib
---

```{r setup}
#| label: setup
#| echo: false
#| cache: false

knitr::opts_chunk$set(echo = TRUE, fig.path='figures/', cache = TRUE, fig.width = 10)
ggplot2::theme_set(ggplot2::theme_bw())
```

```{r libraries}
#| label: libraries
#| message: false
#| cache: false
#| include: false

library(readr)
library(tibble)
#library(feather)
#library(data.table)
#library(dtplyr)
library(dplyr, warn.conflicts = FALSE)
library(tidyr)
library(purrr)
library(stringr)
library(ggplot2)
library(kfigr)
library(knitr)
library(grateful)
library(patchwork)
#library(DT)
#library(reactable)
```

```{r constants}
#| label: constants
GTDB_TAXRANKS    <- c('domain', 'phylum', 'class', 'order', 'family', 'genus', 'species')
ORDERED_TAXRANKS <- c('domain', 'kingdom', 'phylum', 'class', 'order', 'family', 'genus', 'species', 'strain', 'subspecies')
BLAST6_COLNAMES  <- c('qseqid', 'sseqid', 'pident', 'length', 'mismatch', 'gapopen', 'qstart', 'qend', 'sstart', 'send', 'evalue', 'bitscore')
BLAST6_COLTYPES  <- 'ccdiiiiiiidd'
```

```{r read-data}
#| label: read-data
```

# Version history

# Summary

# Introduction

# Materials and Methods

## R and packages

This analysis was run with `r R.version$version.string`. Versions of packages used can be found in @tbl-cite-packages.

```{r tbl-cite-packages}
#| label: tbl-cite-packages
#| cache: false
#| tbl-cap: Versions of R and packages used in this analysis.

cite_packages(output = "table", pkgs = "Session", out.dir = getwd()) %>%
  kable()
```

# Results

# Discussion

# References

```{r}
# vim: sw=2
```
