FETCH_DARDEL = rsync -avhP --size-only dardel:/cfs/klemming/projects/supr/trawl-2025/TRAWL24/trawl24_metatdenovo/results/summary_tables/$@ ./.

all: megahit.prokka.counts.tsv.gz megahit.prokka.gtdb.eukulele.taxonomy.tsv.gz megahit.prokka.mmetsp.eukulele.taxonomy.tsv.gz megahit.prokka.phylodb.eukulele.taxonomy.tsv.gz megahit.prokka.kofamscan.tsv.gz megahit.prokka.ncbi-refseq-20250115.diamond.taxonomy-taxdump.tsv.gz megahit.prokka.overall_stats.tsv.gz megahit.prokka.emapper.tsv.gz megahit.prokka.gtdb-r220.diamond.taxonomy.tsv.gz megahit.prokka.kofamscan-uniq.tsv.gz megahit.prokka.ncbi-refseq-20250115.diamond.taxonomy.tsv.gz megahit.prokka.prokka-annotations.tsv.gz

megahit.prokka.counts.tsv.gz:
	$(FETCH_DARDEL)

megahit.prokka.gtdb.eukulele.taxonomy.tsv.gz:
	$(FETCH_DARDEL)

megahit.prokka.mmetsp.eukulele.taxonomy.tsv.gz:
	$(FETCH_DARDEL)

megahit.prokka.phylodb.eukulele.taxonomy.tsv.gz:
	$(FETCH_DARDEL)

megahit.prokka.kofamscan.tsv.gz:
	$(FETCH_DARDEL)

megahit.prokka.ncbi-refseq-20250115.diamond.taxonomy-taxdump.tsv.gz:
	$(FETCH_DARDEL)

megahit.prokka.overall_stats.tsv.gz:
	$(FETCH_DARDEL)

megahit.prokka.emapper.tsv.gz:
	$(FETCH_DARDEL)

megahit.prokka.gtdb-r220.diamond.taxonomy.tsv.gz:
	$(FETCH_DARDEL)

megahit.prokka.kofamscan-uniq.tsv.gz:
	$(FETCH_DARDEL)

megahit.prokka.ncbi-refseq-20250115.diamond.taxonomy.tsv.gz:
	$(FETCH_DARDEL)

megahit.prokka.prokka-annotations.tsv.gz:
	$(FETCH_DARDEL)
